### ISSUE TITLE
HAVE_NCURSESW_CURSES_H flag set without having the include file

### ISSUE THREAD

**Issue by maki-chan** [rakshasa/rtorrent#886] opened 2019-06-18 11:58 UTC
Due to this commit I am not able to compile rtorrent anymore: https://github.com/rakshasa/rtorrent/commit/9cce5a0bd1b31c1f33cdeb5b402158dbf0ae0bee

The problem is, that with Arch Linux, there is no `<ncursesw/curses.h>` file, but the `HAVE_NCURSESW_CURSES_H` flag gets set and thus I get a compilation error that the file `ncursesw/curses.h` cannot be found.

**Comment by chros73** [comment] 2019-06-18 13:27
It was a [pull request](https://github.com/rakshasa/rtorrent/pull/750) that was merged after 0.9.7 release. You can try to contact @ss23 about this.

**Comment by ss23** [comment] 2019-06-18 17:45
I'm not super familiar with autotools, but `HAVE_NCURSESW_CURSES_H` will only be set if pkgconfig finds it: `PKG_CHECK_MODULES([CURSES],[ncursesw],[...]`. Is there a reason it would be found on your system, but not exist? Do you know if the problem is across multiple arch installs, or just yours?

**Comment by nouman8** [comment] 2019-06-20 03:36
having same issue Arch Linux as well..can't compile rtorrent master branch.

**Comment by maki-chan** [comment] 2019-06-20 07:08
@ss23 Arch Linux has an include file called `/usr/include/cursesw.h`. I don't know if that's the path in Arch Linux for ncursesw support, but it seems to be the case. The package itself can be found here: https://www.archlinux.org/packages/core/x86_64/ncurses/

**Comment by z0z0z** [comment] 2019-06-20 08:12
Also experiencing this, can't compile rtorrent.

Also on Arch.

**Comment by ss23** [comment] 2019-06-27 08:52
I don't have an Arch Linux system to test on, but it looks like some weirdness to do with how they package ncurses: https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/ncurses#n36

I've pushed an attempted fix for this that just checks for ncurses before ncursesw, which may fix it. Could someone try applying https://github.com/ss23/rtorrent/commit/a808d67b1fe28c74a4f6e3b44000fd51f864f11e.patch (or checking out the branch) and seeing if that helps?

**Comment by chros73** [comment] 2019-06-27 09:24
> I don't have an Arch Linux system to test on

You can install it in a VM if it's not trouble.

**Comment by rakshasa** [comment] 2019-07-12 22:30
Should be fixed.

**Closed by rakshasa** 2019-07-12 22:30 UTC

**Comment by nouman8** [comment] 2019-07-13 03:08
just tried, still not compiling on Archlinux.

**Comment by rakshasa** [comment] 2019-07-13 12:39
It seems ax_with_curses.m4 was too old, and the newest version had various issues, so some custom autoconf magic was committed due to broken pkgconfig files in most distros.

Reverted to using only ax_with_curses.m4, and upgraded it from 13 to 16, which is the latest one that seems to work properly.
