### ISSUE TITLE
rtorrent install problem

### ISSUE THREAD

**Issue by csgithubgamer** [rakshasa/rtorrent#1115] opened 2021-09-18 07:26 UTC
sudo apt-get install rtorrent

I can't install rtorrent client, because is no access to this file:
Failed to get http://ftp.fr.debian.org/debian/pool/main/x/xmlrpc-c/libxmlrpc-core-c3_1.16.33-3.2_amd64.deb 404 Not Found [IP: 212.27.32.66 80

How to solve this problem?
Do you have a script for manual installation rtorrent?

**Comment by fckwan** [comment] 2021-11-09 01:25
Did you do sudo apt-get update
You can download the .deb file below.
[https://pkgs.org/download/rtorrent](url)

**Comment by kannibalox** [comment] 2021-11-09 12:48
This is an exact duplicate of #1125 (technically vice versa, but that one's seen more activity)

**Comment by PRESFIL** [comment] 2021-11-10 16:20
@kannibalox , which is duplicate of #1110 .
Is it really so hard to use `apt` for people :smile: ...

**Closed** 2021-11-17 21:28 UTC
