### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by keisko** [rakshasa/rtorrent#137] opened 2013-06-20 08:38 UTC
Hello,

I'm using rTorrent 0.9.2 and LibTorrent 0.13.2.
Our seedbox server has ruTorrent v3.5.

Once we click on STOP button on any torrent, there is no any event send to tracker, only following values:
info_hash
peer_id
key
compact
port 
uploaded 
downloaded 
left

If I re-start the torrent, STARTED event is being sent to tracker, once torrent being completed, COMPLETED event also sends.

On announce inverval update, an empty event sends, this is OK but on stopped torrent there must be a STOPPED event!

**Comment by rakshasa** [comment] 2019-10-01 02:12
Duplicate of #899.

**Closed by rakshasa** 2019-10-01 02:12 UTC
