### ISSUE TITLE
rtorrent 0.9.7 reporting internal ip to the tracker

### ISSUE THREAD

**Issue by Jolar** [rakshasa/rtorrent#731] opened 2018-06-08 06:15 UTC
After upgrading, I noticed there was a (private) tracker that prevented connections to other peers, due to the internal ip on the private subnet being reported together with my external. Setting network.local_address.set to my external ip fixed this, but it seems inconvenient to have to do this, especially if you don't have a fixed ip.

**Comment by chros73** [comment] 2018-06-08 06:27
Thanks for the bug report!
You can/should use [this approach](https://github.com/rakshasa/rtorrent/wiki/Common-Tasks-in-rTorrent#setting-the-local-ip) to prevent the bug.

**Comment by pyroscope** [comment] 2018-06-08 06:58
If that is a regression of 0.9.7, then it should be changed to use `0.0.0.0` or something to get the old behaviour.

**Comment by afontenot** [comment] 2018-07-05 11:03
I believe this commit introduced the bug: https://github.com/rakshasa/libtorrent/commit/d0b7724febec620c43babf08fcb5a6f4148af01c

I'm not quite sure but I believe that there should be `&&` in the conditional. Otherwise the check passes even on ipv4 connections to the tracker, therefore sending whatever libtorrent determines the "local address" is as a parameter.

Even if the bug can be fixed through this change, I suggest it would be a good idea to allow disabling sending an additional local address via the config.

**Comment by PixiBixi** [comment] 2019-01-14 19:10
Hi everyone ! 7 monthes later, the bug is still present, can you merge it ? :/

**Comment by vnpavanelli** [comment] 2019-01-15 21:07
+1 to please merge it :) This bug is really annoying

**Comment by WiperWoper** [comment] 2019-01-31 17:49
Having the same issue, please merge the fix. Thanks.

**Comment by smathev** [comment] 2019-03-26 09:26
Any news about when this fix might be merged?

**Comment by afontenot** [comment] 2019-03-26 21:18
Hi all, in case it's unclear, I just wrote the patch - I'm not one of the developers and I can't merge this myself. Unfortunately they seem to have gone on indefinite hiatus again.

Does anyone know which trackers are affected by this? What is happening here is that in addition to connecting over IPv4, rtorrent is sending another address via `&ipv4=x.x.x.x`. What some trackers are apparently doing is throwing out the implicit good address and accepting the explicit address sent by rtorrent. IMO this is definitely buggy behavior on their part - the explicit address should never differ from the implicit one, especially if the address being sent is a reserved local one (e.g. in 192.168/16). They should just completely ignore the `&ipv4` tag for IPv4 connections. If you have a way of contacting these trackers, or you know what software they're using, reporting this problem upstream may get you better results.

If that isn't an option for you, you can either rebuild rtorrent yourself, or see if one of the following in your `.rtorrent.rc` works for you.

    network.local_address.set = ""
    network.local_address.set = "0.0.0.0"
    network.local_address.set = "127.0.0.1"

**Comment by WiperWoper** [comment] 2019-03-26 22:55
> Does anyone know which trackers are affected by this? 

EMP for me at least.

**Comment by OdinGitDat** [comment] 2019-03-27 03:24
> EMP for me at least.

omg ew...

(same here)

**Comment by smathev** [comment] 2019-03-27 07:35
I know this might be the long way around, but since the [fix mentioned by ](https://github.com/rakshasa/rtorrent/wiki/Common-Tasks-in-rTorrent#setting-the-local-ip) @chros73 isn't working for me, I ended up writing a short bash-script that gets my external IP and leaves that in a txt-file. Unfortunately I can't quite get rtorrent to read the file and set network.local_address.set as the contents of that file.

Any help would be appreciated, what I have so far is:

# Get public IP address without the need of having dynamic DNS service, also works from behind NAT, through tunnel
method.insert = get_public_ip_address, simple|private, "execute.capture=bash,-c,\"cat /ip_chech/ip\""
# The IP address reported to the tracker. (ip) This handles dynamic IP's as well.
schedule2 = ip_tick, 0, 1800, "network.local_address.set=(get_public_ip_address)"

I run the pingcheck-script and rtorrent in separate dockers so /ip_check/ip is a shared folder and file between them.

**Comment by chros73** [comment] 2019-03-27 09:02
> isn't working for me

Which part of it doesn't work? :)

**Comment by smathev** [comment] 2019-03-27 10:26
@chros73 - Hmm, I feel like I had that in my code, but it's clear I lost it when I wrote it here. I've just tried it - using your correction, but it still doesn't work.

The reason your original method isn't working is because the docker-image I'm using doesn't come with dnsutils/dig-command.

I'm not sure how I would "break up the test" to see whether the issue is with the first (method.insert) or second command (schedule2), but since "network.local_adress.set" works as a separate command in itself (IE. network.local_address.set = XXX.XXX.XXX.XXX) I feel like the issue is with the first part (method.insert), but I might be wrong :)

**Comment by chros73** [comment] 2019-03-27 12:26
The whole command (`cat /ip_chech/ip`) needs to return back a string without a newline for `execute.capture`.

You can try out your `get_public_ip_address` method in rtorrent, hit `CTRL+X` then use this command:
`print=$get_public_ip_address=`

**Comment by smathev** [comment] 2019-03-27 14:26
Okay, so, I figured out how to remove the newline in bash, using the command: 
cat /ping_check/ip | tr -d '\n' - my next issue is I can't quite figure out how many escape-characters I need or how to create them. I thought I needed to do like this: 
method.insert = get_public_ip_address, simple|private, "execute.capture=bash,-c,\"eval cat /ip_chech/ip | tr -d '\n' \""

But that isn't quite right, as rtorrent doesn't set the IP correctly. Testing the command in rtorrent gives the following to feedbacks:
When starting or Schedule2 ticks rtorrent says: "Scheduled command failed: ip_tick: Could not set local address: Name does not resolve."
When trying to run the command, as suggested (print=$get_public_ip_address=) it simply reads a blank line - it gives the time of the input/output, but there is nothing in the line.

I'm fairly certain that what I'm missing is a way to remove the newline and correctly escape the sequence of characters needed to do that, am I onto the right path?

I've tried it both with and without eval, and that doesn't change anything.

**Comment by smathev** [comment] 2019-03-27 15:21
Okay, so I've moved past the first issue, getting "get_public_ip_address" to actually give a result. When I run that command now (print=$get_public_ip_address=) it gives me a correct IP, IE. my external IP from the VPN.

The command I've used to get the first bit to resolve is: 
"execute.capture=bash,-c,\"head -n 1 /ip_check/ip \"" - this solves the first bit (getting the first line of a file read into as a variable).

However, the schedule2 still fails. The output I get from that is:
"Scheduled command failed: ip_tick: Could not set local address: Name does not resolve."

**Comment by afontenot** [comment] 2019-03-27 23:16
Just to reiterate, you shouldn't need any scripts - `&ipv4` is an optional parameter. At least one of the following in your config should get you the old libtorrent 0.13.6 behavior:

   network.local_address.set = ""
   network.local_address.set = "0.0.0.0"
   network.local_address.set = "127.0.0.1"

See if your tracker admins can fix this for you.

**Comment by smathev** [comment] 2019-03-28 08:15
Hi @afontenot - thanks for your solution, it seems to have solved the issue of the tracker status being "Invalid IP detected" when I use network.local_address.set = 127.0.0.1 .

However, this keeps rtorrent reporting two IP's to the tracker. I've tested it with http://ipmagnet.services.cbcdn.com - where it reports two IP's to the tracker:

Timestamp               | IP address(es)                     | User Agent
--                              | --                                        | --
28.03.2019 08:35:19 | (MyVpnIP), 127.0.0.1           | rtorrent/0.9.7/0.13.7

So, I prefer the method of using a script to set the network.adress to only my external IP - but I might not undertand why rtorrent needs to report my internal IP too?

**Comment by smathev** [comment] 2019-03-28 08:43
Update - the issue has been solved. 

I reinvestigated the output I got from `"execute.capture=bash,-c,"head -n 1 /ip_check/ip ""`. As is turns out there was a $ at the end of the file that wasn't printed until I checked using `cat -A /ping_check/ip.` 

So, re-doing the `execute.capture`-command to be:
` "execute.capture=bash,-c,\"head -c -1 /ip_check/ip \""` has solved the issue. I now have rtorrent only reporting one IP to the tracker, and that IP is the IP contained in the file created by my ping_check-docker.

**Comment by johnyb0y** [comment] 2019-06-08 18:13
@afontenot Wanted to say thanks! Manually inserted your commit and rebuilt libtorrent.

I do have one question: 
My rtorrent is running on a dual stack connection and without your fix rtorrent reported 3 IPs to the tracker (tested this [here](https://torguard.net/checkmytorrentipaddress.php)): 
**External IPv4, External IPv6, Internal IPv4** 

After using your fix rtorrent is only reporting the **External IPv4**, not the External IPv6. 
Is this expected behavior?
Thanks!

**Closed** 2019-06-09 05:32 UTC
