### ISSUE TITLE
rtorrent 0.9.7 does not IPv4 support?

### ISSUE THREAD

**Issue by mopo3ilo** [rakshasa/rtorrent#733] opened 2018-06-09 10:24 UTC
In rtorrent.rc
`scgi_port = 127.0.0.1:5000`
Open port on IPv6
`[::ffff:127.0.0.1]:5000`

**Comment by pyroscope** [comment] 2018-06-09 10:32
Dupe of #732

**Closed** 2018-08-31 06:47 UTC
