### ISSUE TITLE
100% CPU usage and non-functional rtorrent

### ISSUE THREAD

**Issue by z0z0z** [rakshasa/rtorrent#501] opened 2016-09-09 03:27 UTC
I've been using rtorrent with no problems for years, but since a few weeks ago I've been having this problem.

I start rtorrent, everything works fine, but then after about an hour or so rtorrent starts using 100% CPU on 1 thread, and is completely non-functional (it won't actually seed or download torrents, ncurses interface freezes, I can't get through to it from rutorrent, and I have to send SIGKILL to end the process). This happens everytime consistently, 100% reproducible every run of rtorrent.

I am seeding quite a lot of torrents, 780 to be exact. Perhaps this is happening because at some point in the past few weeks I started seeding a bad torrent which causes this bug, or I'm seeding too many?

I have updated to a build from git, and tried the latest stable versions of libtorrent/rtorrent. I'm not aware of any changes I've made that could have started causing this behavior, it just started happening.

I've checked all my hard drives for failure and they're fine. I am running kernel 4.7.2, using the latest unstable versions of relevant packages in the Gentoo repos.

**Comment by ratpenat** [comment] 2016-09-09 09:15
Make sure you have curl linked with openssl instead of nss  (enable curl_ssl_openssl use flag for net-misc/curl). For the versions currently on the unstable branch, curl + nss gives problems. See issue #457

**Comment by z0z0z** [comment] 2016-09-09 18:40
Rebuilding curl with openssl instead of nss solved the problem.

Thank you very much. Something upstream should probably be done to warn/inform users of this. A lot more people may start running into this problem, it's been driving me a bit mad over the past weeks.

**Comment by rakshasa** [comment] 2016-12-29 03:54
Duplicate of #457.

**Closed by rakshasa** 2016-12-29 03:54 UTC
