### ISSUE TITLE
new version of curl causes timeouts on https trackers

### ISSUE THREAD

**Issue by rezad1393** [rakshasa/rtorrent#538] opened 2016-12-28 18:35 UTC
I use rtorrent on an arm odroid board. 
recently I saw a lot of timeouts. after investigating it seemed that it happened with https trackers.
downgrading curl to 7.51.0 seems to fixes this issue.
but I don't think this is curl issue cause using curl in terminal with the tracker parameters work in https url.
is this an issue with rtorrent packages on archlinuxarm repo for odroid or rtorrent or curl bug?
anybody else has this issue?

**Comment by Micdu70** [comment] 2016-12-28 18:52
Hello,
I think everyone have this issue with curl version 7.52.1... ( I have it on Debian 8 and see comments here: #535 )
This will require some investigation...

**Comment by pyroscope** [comment] 2016-12-28 19:26
Any reports related to this should mention the underlying TLS library (openssl or gnutls or maybe even others).

**Comment by rakshasa** [comment] 2016-12-29 03:38
Duplicate of #535, and do report the issue to the curl people.

**Closed by rakshasa** 2016-12-29 03:38 UTC

**Comment by rezad1393** [comment] 2016-12-29 21:32
I didn't find a github page that was for curl to report this (there was one but it was a mirror for code only) and I am tired of creating account on a website whenever I want to report just one bug.

btw as I said using the curl to get that tracker response works outside of rtorrent ( in terminal ) ,though that is just testing a simple url so maybe not that great. but this point the issue toward rtorrent instead curl.
maybe the implementation is wrong?
I am not a programer so I am not familiar with these stuff but how does rtorrent use curl for tracker announce? is it something non-standard?

 BTW shoudnt rtorrent use libcurl instead of curl? maybe I am missing something.

**Comment by rakshasa** [comment] 2016-12-30 03:29
I've already posted to their mailing list.

**Comment by rezad1393** [comment] 2016-12-30 23:04
UPDATE: updating to the new build of curl on archlinuxarm seems to have fixed the issue (https tracker timeouts)

**Comment by rezad1393** [comment] 2016-12-31 17:54
the diff update for building on archlinux says this bug is gone
[](https://git.archlinux.org/svntogit/packages.git/commit/trunk?h=packages/curl&id=bae58314ffe16b0642811fdb0187a9b8eba8d362)
